sudo: false
language: ruby
cache: bundler
bundler_args: --without development

rvm:
  - ruby-head
  - 2.5.0
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - jruby-9.1.9.0

services:
  - docker

matrix:
  fast_finish: true

before_install:
  # Bundler on Travis may be too out of date
  # Update bundler to a recent version.
  - gem install bundler
deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    rvm: "2.4.0"
