sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - ruby-head
  - ruby
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-head
  - jruby
  - jruby-19mode
  - rbx-head
  - rbx-2
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby
    - rvm: jruby-head
    - rvm: jruby
    - rvm: rbx-head
