language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - ruby-head
  - ruby
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-head
  - jruby
  - jruby-19mode
  - jruby-18mode
  - rbx-head
  - rbx-2
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby
    - rvm: jruby-head
    - rvm: jruby
    - rvm: rbx-head